import type {Metadata} from "next";
import {Poppins, Noto_Sans_KR} from 'next/font/google';
import "./globals.css";
import React from "react";

const poppins = Poppins({
    variable: '--font-poppins',
    subsets: ['latin'],
    weight: ['400'],
    display: 'swap',
    preload: true,
});

const noto = Noto_Sans_KR({
    variable: '--font-noto',
    subsets: ['latin'],
    display: 'swap',
    preload: true,
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${poppins.variable} ${noto.variable} antialiased`}>
        {children}
        </body>
        </html>
    );
}
