import type { Metadata } from 'next';
import { Poppins, Cute_Font, Noto_Sans_KR, Fira_Code } from 'next/font/google';
import './globals.css';
import NavMenu from '@/menus/NavMenu';
import { AuthProvider } from '@/lib/AuthContext';
import { SnackbarProvider } from '@/lib/SnackbarContext';
import { CssBaseline } from '@mui/material';

const noto = Noto_Sans_KR({
  variable: '--font-noto',
  subsets: ['latin'],
  display: 'swap',
  preload: false,
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
  preload: false,
});

const cute = Cute_Font({
  variable: '--font-cute',
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
  preload: false,
});

const fira = Fira_Code({
  variable: '--font-fira-code',
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
  preload: false,
});

export const metadata: Metadata = {
  title: 'I AM KIM BUM JUN',
  description: 'Generated by create BJ',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preconnect"
          href="https://fonts.googleapis.com"
        />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
        />
      </head>
      <body
        className={`${noto.variable}
        ${cute.variable}
        ${poppins.variable}
        ${fira.variable}
        antialiased`}>
        <AuthProvider>
          <SnackbarProvider>

            <div className="w-full h-[72px] bg-sky-900">
              <NavMenu />
            </div>
            <main className="min-h-screen bg-slate-50">{children}</main>
          </SnackbarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
