import type { Metadata } from "next";
import { Inter, Roboto, IBM_Plex_Sans_KR, Oswald, Fira_Code, Cute_Font } from "next/font/google";
import "./globals.css";

import Navbar from "./navbar/Navbar";
import Footer from "./footer/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: "swap",
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: "swap",
});

const fira = Fira_Code({
  variable: "--font-fira",
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap'
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: "swap",
})

const ibm_plex = IBM_Plex_Sans_KR({
  variable: "--font-ibm-plex-kr",
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: "swap"
});

const cute = Cute_Font({
  variable: "--font-cute",
  weight: '400',
  subsets: ['latin'],
  display: "swap"
})

export const metadata: Metadata = {
  metadataBase: new URL('https://writer.or.kr'),
  title: {
    default: 'Writer',
    template: '%s | Writer',
    absolute: ''
  },
  description: "Generated by BJ - KIM BUM JUN",
  icons: {
    icon: '/favicons/favicon.ico',
  },
  keywords: '글, 글나눔, Text, Writer',
  openGraph: {
    title: 'Writer',
    description: '글 마당에 오신 것을 환영합니다..',
    url: '/',
    images: ['/images/write.webp'],
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`
          ${inter.variable}
          ${roboto.variable}
          ${fira.variable}
          ${ibm_plex.variable}
          ${oswald.variable}
          ${cute.variable}
          antialiased
          md:subpixel-antialiased`}
      >
        <div className="writer-container">
          <header> <Navbar /> </header>
          <main> {children} </main>
          <footer> <Footer /> </footer>
        </div>
      </body>
    </html>
  );

}
