import type { Metadata } from "next";
// import { Roboto, IBM_Plex_Sans_KR, Poppins, Fira_Code } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css";

import Navbar from "./navbar/Navbar";
import Footer from "./footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  metadataBase: new URL('https://writer.or.kr'),
  title: {
    default: 'Writer',
    template: '%s | Writer',
    absolute: ''
  },
  description: "Generated by BJ - KIM BUM JUN",
  icons: {
    icon: '/favicons/favicon.ico',
  },
  keywords: '글, 글나눔, Text, Writer',
  openGraph: {
    title: 'Writer',
    description: '글 마당에 오신 것을 환영합니다..',
    url: '/',
    images: ['/images/write.webp'],
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`

          ${geistSans.variable} ${geistMono.variable}
          antialiased`}
      >
        <div className="writer-container">
          <header> <Navbar /> </header>
          <main> {children} </main>
          <footer> <Footer /> </footer>
        </div>
      </body>
    </html>
  );
}
